export const NORMAL_JOB = [
  {
    id: "2",
    sourceLogo: require("../../assets/images/jobs/job2.png"),
    jobTitle: "Senior Mobile Engineer",
    sourceName: "X",
    city: "California, USA",
    jobTime: "Part time",
    amount: 200,
    inBookmark: true,
    workingType: "hr",
    type: 2,
  },
  {
    id: "3",
    sourceLogo: require("../../assets/images/jobs/job3.png"),
    jobTitle: "Joomla Developer",
    sourceName: "Microsoft Crop",
    city: "California, USA",
    jobTime: "Full time",
    amount: 300,
    inBookmark: true,
    workingType: "hr",
    type: 3,
  },
  {
    id: "4",
    sourceLogo: require("../../assets/images/jobs/job4.png"),
    jobTitle: "Operation Manager",
    sourceName: "Linkedin",
    city: "California, USA",
    jobTime: "Full time",
    amount: 400,
    inBookmark: true,
    workingType: "hr",
    type: 3,
  },
  {
    id: "5",
    sourceLogo: require("../../assets/images/jobs/job5.png"),
    jobTitle: "UI/UX Designer",
    sourceName: "Android",
    city: "California, USA",
    jobTime: "Full time",
    amount: 500,
    inBookmark: false,
    workingType: "hr",
    type: 3,
  },
  {
    id: "6",
    sourceLogo: require("../../assets/images/jobs/job6.png"),
    jobTitle: "Senior Mobile Engineer",
    sourceName: "Robotflow",
    city: "California, USA",
    jobTime: "Part time",
    amount: 600,
    inBookmark: false,
    workingType: "hr",
    type: 3,
  },
  {
    id: "7",
    sourceLogo: require("../../assets/images/jobs/job7.png"),
    jobTitle: "Product Manager",
    sourceName: "Wipro",
    city: "California, USA",
    jobTime: "Part time",
    amount: 700,
    inBookmark: false,
    workingType: "hr",
    type: 3,
  },
  {
    id: "8",
    sourceLogo: require("../../assets/images/jobs/job8.png"),
    jobTitle: "Java Backend Engineer",
    sourceName: "BlownUp",
    city: "California, USA",
    jobTime: "Part time",
    amount: 800,
    inBookmark: false,
    workingType: "hr",
    type: 3,
  },
];

export const ADVERTISEMENTS_JOB = {
  id: "1",
  sourceLogo: require("../../assets/images/users/profile_banner.jpg"),
  name: "Nordson Torches",
};

export const FEATURED_JOB = {
  id: "1",
  sourceLogo: require("../../assets/images/jobs/job1.png"),
  jobTitle: "Backend Engineer",
  jobDescription:
    "This text is styled with some of the text formatting properties. The heading uses the text-align, text-transform, and color properties. The paragraph is indented, aligned, and the space between characters is specified. The underline is removed from this colored",
  sourceName: "PIEXEX",
  city: "Fort worth, USA",
  jobTime: "Full time",
  amount: 100,
  inBookmark: true,
  workingType: "hr",
  type: 1,
};
